<?php
use function Naf\Form\csrf;
use function Naf\Form\error;
use function Naf\Form\memory;
use function Naf\route;
?>

<?php $this->setLayout('layout') ?>

<?php $this->block('content'); ?>

<div class="wrap">

    <div class="container bg-dark p-2">

    <form action="<?= route('contact') ?>" method="post">

        <div class="grid">
            <label for="firstname">Vorname:</label>
            <input id="firstname" type="text" name="firstname" value="<?= memory('firstname') ?>" />
            <?= error('firstname', $check) ?>

            <label for="lastname">Nachname:</label>
            <input id="lastname" type="text" name="lastname" value="<?= memory('lastname') ?>" />
            <?= error('lastname', $check) ?>

            <label for="message">Nachricht:</label>
            <textarea id="message" name="message" rows="5" cols="50"><?= memory('message') ?></textarea>
            <?= error('message', $check) ?>
        </div>

        <input type="hidden" name="_csrf" value="<?= csrf()->generate() ?>" />

        <hr />

        <button>Abschicken</button>

    </form>

    </div>

</div>

<?php $this->endblock('content') ?>
